For my data mining assignment, I used https://nijianmo.github.io/amazon/index.html. I used the smaller subset of the "Magazines Subscriptions" dataset. I used code given in the link above, to import the dataset and convert it into a Pandas DataFrame.

In [1]:
import requests
import json
import pandas as pd
import numpy as np
import gzip

In [2]:
def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield json.loads(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

df = getDF('Magazine_Subscriptions_5.json.gz')

In [3]:
df

overall  verified   reviewTime      reviewerID        asin  \
0         4.0      True  02 26, 2014   A5QQOOZJOVPSF  B00005N7P0   
1         5.0     False   03 6, 2004   A5RHZE7B8SV5Q  B00005N7PS   
2         1.0     False  07 15, 2003   A1RPTVW5VEOSI  B00005N7PS   
3         1.0      True  01 31, 2015  A1SFRBCMW8XVBW  B00005N7PS   
4         5.0      True   10 5, 2010  A1IU9VPCBKZPE8  B00005N7P0   
...       ...       ...          ...             ...         ...   
2370      1.0      True   02 7, 2018  A18X3E6V8DGIDZ  B00X6LREJU   
2371      4.0      True   03 3, 2017  A1Y98LVYJ0YZJ0  B00X6LREHM   
2372      5.0      True  01 15, 2017  A1VTKYW3YQEHTN  B00X6LREHM   
2373      5.0      True  05 30, 2017   ASU7EOBD3Y4BV  B01HI8V10E   
2374      4.0      True  01 16, 2017  A3O652WDKMZCQL  B01HI8V10E   

            reviewerName                                         reviewText  \
0      John L. Mehlmauer  I'm old, and so is my computer.  Any advice th...   
1         gorillazfan249  There's nothing to say, but if you want a REAL...   
2     Michael J. Edelman  If you're the kind of man who looks at himself...   
3      Hoyett L. Barnett  Nothing to it.  Just an advertisement.  Little...   
4           Randolph Eck  When PC Magazine ceased publication of their p...   
...                  ...                                                ...   
2370          gatormum64  Not what I expected. Found it boring and lacki...   
2371             Michele  I have been a Family Circle readers for years ...   
2372               Linda  Even though I have only received 3 issues, I r...   
2373          Miss Betty    Great magazine at a great price through Amazon!   
2374             D. Lyon  Nice pictures and some good recipes.  Might co...   

                                                summary  unixReviewTime vote  \
0                                     Cheapskates guide      1393372800  NaN   
1                       The best mature Men's magazine.      1078531200    3   
2               THE Magazine for the Self-Centered Male      1058227200   17   
3     Nothing to it. Just an advertisement. Little a...      1422662400  NaN   
4                           Excellent Computer Magazine      1286236800    2   
...                                                 ...             ...  ...   
2370                              Cancelled subscripton      1517961600  NaN   
2371            You can find a good variety of articles      1488499200  NaN   
2372               I really enjoy reading Family Circle      1484438400  NaN   
2373    Great magazine at a great price through Amazon!      1496102400  NaN   
2374                                        PRETTY GOOD      1484524800  NaN   

     style image  
0      NaN   NaN  
1      NaN   NaN  
2      NaN   NaN  
3      NaN   NaN  
4      NaN   NaN  
...    ...   ...  
2370   NaN   NaN  
2371   NaN   NaN  
2372   NaN   NaN  
2373   NaN   NaN  
2374   NaN   NaN  

[2375 rows x 12 columns]

In [4]:
reviews = df[['overall', 'reviewText']]

In [5]:
reviews

overall                                         reviewText
0         4.0  I'm old, and so is my computer.  Any advice th...
1         5.0  There's nothing to say, but if you want a REAL...
2         1.0  If you're the kind of man who looks at himself...
3         1.0  Nothing to it.  Just an advertisement.  Little...
4         5.0  When PC Magazine ceased publication of their p...
...       ...                                                ...
2370      1.0  Not what I expected. Found it boring and lacki...
2371      4.0  I have been a Family Circle readers for years ...
2372      5.0  Even though I have only received 3 issues, I r...
2373      5.0    Great magazine at a great price through Amazon!
2374      4.0  Nice pictures and some good recipes.  Might co...

[2375 rows x 2 columns]

In [6]:
reviews.isnull().sum()

overall       0
reviewText    1
dtype: int64

In [7]:
reviews = reviews.dropna()
reviews.isnull().sum()

overall       0
reviewText    0
dtype: int64

In [8]:
X = reviews[['reviewText']]
y = reviews['overall']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [10]:
X_train.shape

(1780, 1)

In [11]:
X_test.shape

(594, 1)

### CountVectorizer

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [13]:
cv = CountVectorizer(stop_words='english')

In [14]:
X_train_cv = cv.fit_transform(X_train['reviewText'])
X_train_cv

<1780x7252 sparse matrix of type '<class 'numpy.int64'>'
	with 39024 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
X_test_cv = cv.transform(X_test['reviewText'])
X_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### CountVectorizer and SVC

In [17]:
from sklearn.svm import SVC
cv_svc = SVC(gamma='scale')
cv_svc.fit(X_train_cv, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [18]:
cv_svc.predict(X_test_cv)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 2., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 3., 5., 5., 5., 5., 5., 5., 4., 5.,
       5., 5., 5., 5., 5., 5., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5.

### Evaluation

In [19]:
cv_svc_score= cv_svc.score(X_test_cv, y_test)
cv_svc_score

0.6936026936026936

### TFID Vectorizer

In [20]:
tfid = TfidfVectorizer(stop_words='english')

In [21]:
X_train_tfid = tfid.fit_transform(X_train['reviewText'])
X_train_tfid
X_test_tfid = tfid.transform(X_test['reviewText'])
X_test_tfid.toarray()
X_train_tfid.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
from sklearn.svm import SVC
tfid_svc = SVC(gamma='scale')
tfid_svc.fit(X_train_tfid, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
y_pred_tfid_svc = tfid_svc.predict(X_test_tfid)

In [24]:
tfid_svc_score = tfid_svc.score(X_test_tfid, y_test)
tfid_svc_score

0.7491582491582491

### GridSearchCV for CV

In [25]:
from sklearn.model_selection import GridSearchCV

In [64]:
cv_grid = {'C':[0.1,0.5, 1,2,3,4,5,6,7,10, 20,50,100,1000],
        'gamma': ['scale'],
        'kernel':['linear','rbf']}

In [65]:
gs_cv = GridSearchCV(cv_svc, cv_grid, n_jobs=-1)

In [66]:
gs_cv.fit(X_train_cv, y_train)

/Users/nhidiep/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1, 2, 3, 4, 5, 6, 7, 10, 20, 50, 100,
                               1000],
                         'gamma': ['scale'], 'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [67]:
gs_cv.best_params_

{'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}

In [30]:
pd.DataFrame(gs_cv.cv_results_).sort_values('rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
9        0.382479      0.009914         0.116348        0.001737       5   
7        0.382252      0.007757         0.115523        0.000532       4   
15       0.409667      0.028755         0.132191        0.023461      10   
13       0.392189      0.002345         0.116250        0.002034       7   
11       0.391856      0.002591         0.117051        0.001722       6   
5        0.379543      0.001879         0.118308        0.002646       3   
3        0.369930      0.006679         0.114769        0.001872       2   
17       0.435668      0.029091         0.136728        0.020146      50   
0        0.287773      0.001169         0.075941        0.000643       1   
1        0.366894      0.001169         0.114039        0.003778       1   
2        0.277556      0.006638         0.073740        0.001587       2   
19       0.405698      0.020837         0.111360        0.001065     100   
4        0.268795      0.000591         0.071500        0.000901       3   
21       0.361619      0.020167         0.090157        0.009499    1000   
6        0.274991      0.006792         0.071052        0.001017       4   
8        0.271693      0.005767         0.071931        0.001390       5   
12       0.282490      0.012083         0.072127        0.001944       7   
10       0.280303      0.008217         0.072008        0.001803       6   
14       0.284327      0.016331         0.070561        0.001078      10   
20       0.442649      0.021804         0.065774        0.003008    1000   
16       0.342647      0.038081         0.086639        0.012066      50   
18       0.422512      0.005544         0.070788        0.002088     100   

   param_gamma param_kernel  \
9        scale          rbf   
7        scale          rbf   
15       scale          rbf   
13       scale          rbf   
11       scale          rbf   
5        scale          rbf   
3        scale          rbf   
17       scale          rbf   
0        scale       linear   
1        scale          rbf   
2        scale       linear   
19       scale          rbf   
4        scale       linear   
21       scale          rbf   
6        scale       linear   
8        scale       linear   
12       scale       linear   
10       scale       linear   
14       scale       linear   
20       scale       linear   
16       scale       linear   
18       scale       linear   

                                               params  split0_test_score  \
9         {'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}           0.677311   
7         {'C': 4, 'gamma': 'scale', 'kernel': 'rbf'}           0.678992   
15       {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}           0.665546   
13        {'C': 7, 'gamma': 'scale', 'kernel': 'rbf'}           0.663866   
11        {'C': 6, 'gamma': 'scale', 'kernel': 'rbf'}           0.658824   
5         {'C': 3, 'gamma': 'scale', 'kernel': 'rbf'}           0.665546   
3         {'C': 2, 'gamma': 'scale', 'kernel': 'rbf'}           0.658824   
17       {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}           0.650420   
0      {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}           0.630252   
1         {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}           0.648739   
2      {'C': 2, 'gamma': 'scale', 'kernel': 'linear'}           0.631933   
19      {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}           0.633613   
4      {'C': 3, 'gamma': 'scale', 'kernel': 'linear'}           0.628571   
21     {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}           0.623529   
6      {'C': 4, 'gamma': 'scale', 'kernel': 'linear'}           0.615126   
8      {'C': 5, 'gamma': 'scale', 'kernel': 'linear'}           0.605042   
12     {'C': 7, 'gamma': 'scale', 'kernel': 'linear'}           0.598319   
10     {'C': 6, 'gamma': 'scale', 'kernel': 'linear'}           0.606723   
14    {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}           0.600000   
20  {'C': 1000, 'gamm

### GridSearchCV for TFID

In [60]:
tfid_grid = {'C':[0.1, 0.5, 1,2,3,4,5,6,7,10,20,50,100,1000],
        'gamma': ['scale'],
        'kernel':['linear','rbf']}

In [61]:
gs_tfid = GridSearchCV(tfid_svc, tfid_grid, n_jobs=-1)

In [62]:
gs_tfid.fit(X_train_tfid, y_train)

/Users/nhidiep/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1, 2, 3, 4, 5, 6, 7, 10, 20, 50, 100,
                               1000],
                         'gamma': ['scale'], 'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [63]:
gs_tfid.best_params_

{'C': 2, 'gamma': 'scale', 'kernel': 'linear'}

In [35]:
gs_tfid.predict(X_test_tfid)

array([5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 3., 5., 5., 2., 5.,
       1., 5., 3., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 4., 3., 4., 5.,
       4., 3., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 3.,
       3., 5., 5., 5., 3., 3., 2., 5., 5., 5., 5., 5., 5., 4., 5., 4., 5.,
       3., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 4.,
       5., 5., 5., 5., 4., 4., 5., 5., 4., 4., 5., 4., 5., 1., 4., 5., 5.,
       5., 5., 5., 3., 5., 5., 5., 5., 5., 5., 3., 5., 3., 5., 5., 5., 5.,
       4., 5., 5., 5., 4., 1., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 3., 5., 5., 4., 5., 3., 5., 5., 5., 5., 5., 5., 4., 5.,
       5., 5., 5., 5., 5., 5., 1., 5., 5., 5., 5., 3., 5., 4., 5., 4., 2.,
       5., 4., 5., 5., 5., 3., 5., 5., 5., 5., 4., 5., 5., 5., 3., 5., 5.,
       5., 5., 5., 5., 3., 3., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5.,
       4., 5., 5., 5., 5.

In [36]:
pd.DataFrame(gs_tfid.cv_results_).sort_values('rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
2        0.386042      0.027725         0.090803        0.002228       2   
3        0.516824      0.023042         0.148130        0.010530       2   
5        0.530840      0.008517         0.127872        0.008375       3   
7        0.538354      0.023811         0.120540        0.001578       4   
21       0.424029      0.023579         0.079743        0.001220    1000   
4        0.376485      0.015410         0.095741        0.014761       3   
19       0.479306      0.006253         0.117684        0.005799     100   
9        0.506563      0.027909         0.137711        0.015167       5   
17       0.483566      0.004190         0.123532        0.002008      50   
11       0.526757      0.027897         0.123435        0.000471       6   
15       0.489934      0.009033         0.123931        0.000966      10   
13       0.498433      0.024658         0.135401        0.012263       7   
6        0.386489      0.009586         0.086168        0.003207       4   
1        0.540981      0.005736         0.126096        0.003790       1   
0        0.348093      0.004031         0.103444        0.007798       1   
8        0.348988      0.002924         0.082119        0.001088       5   
10       0.415769      0.017100         0.090251        0.008555       6   
12       0.363455      0.009861         0.082698        0.001813       7   
14       0.364233      0.004100         0.085195        0.004334      10   
16       0.385410      0.014438         0.082219        0.001025      50   
20       0.580153      0.200076         0.069162        0.011548    1000   
18       0.389999      0.022186         0.081166        0.001188     100   

   param_gamma param_kernel  \
2        scale       linear   
3        scale          rbf   
5        scale          rbf   
7        scale          rbf   
21       scale          rbf   
4        scale       linear   
19       scale          rbf   
9        scale          rbf   
17       scale          rbf   
11       scale          rbf   
15       scale          rbf   
13       scale          rbf   
6        scale       linear   
1        scale          rbf   
0        scale       linear   
8        scale       linear   
10       scale       linear   
12       scale       linear   
14       scale       linear   
16       scale       linear   
20       scale       linear   
18       scale       linear   

                                               params  split0_test_score  \
2      {'C': 2, 'gamma': 'scale', 'kernel': 'linear'}           0.670588   
3         {'C': 2, 'gamma': 'scale', 'kernel': 'rbf'}           0.680672   
5         {'C': 3, 'gamma': 'scale', 'kernel': 'rbf'}           0.680672   
7         {'C': 4, 'gamma': 'scale', 'kernel': 'rbf'}           0.677311   
21     {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
4      {'C': 3, 'gamma': 'scale', 'kernel': 'linear'}           0.665546   
19      {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
9         {'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
17       {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
11        {'C': 6, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
15       {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
13        {'C': 7, 'gamma': 'scale', 'kernel': 'rbf'}           0.673950   
6      {'C': 4, 'gamma': 'scale', 'kernel': 'linear'}           0.665546   
1         {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}           0.668908   
0      {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}           0.672269   
8      {'C': 5, 'gamma': 'scale', 'kernel': 'linear'}           0.662185   
10     {'C': 6, 'gamma': 'scale', 'kernel': 'linear'}           0.662185   
12     {'C': 7, 'gamma': 'scale', 'kernel': 'linear'}           0.657143   
14    {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}           0.653782   
16    {'C': 50, 'gamm

### New Model with Parameters from GridSearchCV

In [56]:
from sklearn.svm import SVC
cv_svc2 = SVC(C=5,kernel='rbf',gamma='scale')
cv_svc2.fit(X_train_cv, y_train)

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [57]:
cv_svc2.score(X_test_cv, y_test)

0.734006734006734

In [58]:
from sklearn.svm import SVC
tfid_svc2 = SVC(C=2,kernel='rbf',gamma='scale')
tfid_svc2.fit(X_train_tfid, y_train)

SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [59]:
tfid_svc2.score(X_test_tfid, y_test)

0.765993265993266